import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { CaseWithDetails, getCaseTimelineEventsByCaseId } from '../DataBase';
import { formatDate } from './commonFunctions';

/**
 * Generates a beautiful case summary and timeline PDF and opens the sharing dialog.
 * 
 * @param caseDetails The case details object
 */
export const exportCaseToPdf = async (caseDetails: CaseWithDetails): Promise<void> => {
  try {
    const timelineEvents = await getCaseTimelineEventsByCaseId(caseDetails.id);
    
    let timelineHtml = '';
    if (timelineEvents.length > 0) {
      timelineEvents.forEach(event => {
        timelineHtml += `
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #ddd; font-weight: bold; width: 120px;">
              ${formatDate(event.hearing_date)}
            </td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">
              ${event.notes || 'No notes added'}
            </td>
          </tr>
        `;
      });
    } else {
      timelineHtml = `
        <tr>
          <td colspan="2" style="padding: 20px; text-align: center; color: #666; font-style: italic;">
            No hearings logged in history.
          </td>
        </tr>
      `;
    }

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <style>
            body {
              font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
              color: #333;
              line-height: 1.5;
              padding: 20px;
            }
            .header {
              text-align: center;
              border-bottom: 2px solid #3B82F6;
              padding-bottom: 15px;
              margin-bottom: 25px;
            }
            .header h1 {
              margin: 0;
              color: #1E3A8A;
              font-size: 26px;
            }
            .header p {
              margin: 5px 0 0 0;
              color: #666;
              font-size: 14px;
            }
            .section {
              margin-bottom: 25px;
            }
            .section-title {
              font-size: 18px;
              color: #1E3A8A;
              border-bottom: 1px solid #3B82F6;
              padding-bottom: 5px;
              margin-bottom: 12px;
              text-transform: uppercase;
              letter-spacing: 0.5px;
            }
            .info-grid {
              display: grid;
              grid-template-columns: 1fr 1fr;
              gap: 15px;
            }
            .info-item {
              margin-bottom: 10px;
            }
            .info-label {
              font-weight: bold;
              color: #555;
              font-size: 12px;
              text-transform: uppercase;
            }
            .info-value {
              font-size: 15px;
              color: #111;
              margin-top: 2px;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 10px;
            }
            th {
              background-color: #F3F4F6;
              color: #1E3A8A;
              text-align: left;
              padding: 10px;
              font-weight: bold;
              border-bottom: 2px solid #ddd;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>CASE SUMMARY SHEET</h1>
            <p>Generated by CaseDiary Application</p>
          </div>
          
          <div class="section">
            <div class="section-title">Case Metadata</div>
            <div class="info-grid">
              <div class="info-item">
                <div class="info-label">Case Title</div>
                <div class="info-value" style="font-weight: bold; font-size: 17px;">${caseDetails.CaseTitle || 'N/A'}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Client Name</div>
                <div class="info-value">${caseDetails.ClientName || 'N/A'}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Case Number / Year</div>
                <div class="info-value">${caseDetails.case_number || 'N/A'} / ${caseDetails.case_year || 'N/A'}</div>
              </div>
              <div class="info-item">
                <div class="info-label">CNR Number</div>
                <div class="info-value">${caseDetails.CNRNumber || 'N/A'}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Court Name</div>
                <div class="info-value">${caseDetails.court_name || 'N/A'}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Case Type</div>
                <div class="info-value">${caseDetails.case_type_name || 'N/A'}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Next Hearing Date</div>
                <div class="info-value" style="color: #EF4444; font-weight: bold;">${formatDate(caseDetails.NextDate)}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Status</div>
                <div class="info-value">${caseDetails.CaseStatus || 'N/A'}</div>
              </div>
            </div>
          </div>

          <div class="section">
            <div class="section-title">Timeline & Hearing History</div>
            <table>
              <thead>
                <tr>
                  <th>Hearing Date</th>
                  <th>Notes / Updates</th>
                </tr>
              </thead>
              <tbody>
                ${timelineHtml}
              </tbody>
            </table>
          </div>
        </body>
      </html>
    `;

    // 1. Render HTML template to PDF file
    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    
    // 2. Open sharing panel
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: `Export_${caseDetails.CaseTitle || 'Case'}`,
        UTI: 'com.adobe.pdf',
      });
    } else {
      console.warn("PDF sharing is not available on this platform.");
    }
  } catch (error) {
    console.error("Failed to export case to PDF:", error);
    throw error;
  }
};

/**
 * Exports today's cause list of cases to a structured PDF for junior advocates.
 * Includes a blank 'Notes' column on the right for manual handwriting.
 */
export const exportDailyCauseListToPdf = async (cases: any[], titleDate: string): Promise<void> => {
  try {
    let rowsHtml = '';
    if (cases.length > 0) {
      cases.forEach((c, index) => {
        rowsHtml += `
          <tr>
            <td style="padding: 8px; border: 1px solid #aaa; text-align: center; font-size: 11px;">
              ${index + 1}
            </td>
            <td style="padding: 8px; border: 1px solid #aaa; font-size: 12px; font-weight: bold;">
              ${c.CaseTitle || 'No Title'}<br/>
              <span style="font-size: 10px; color: #555; font-weight: normal;">
                CNR: ${c.CNRNumber || 'N/A'}<br/>
                Client: ${c.ClientName || 'N/A'} (${c.ClientContactNumber || 'N/A'})
              </span>
            </td>
            <td style="padding: 8px; border: 1px solid #aaa; font-size: 11px;">
              ${c.court_name || 'N/A'}<br/>
              <span style="font-size: 10px; color: #555;">${c.JudgeName || ''}</span>
            </td>
            <td style="padding: 8px; border: 1px solid #aaa; font-size: 11px; text-align: center;">
              ${c.PreviousDate ? formatDate(c.PreviousDate) : 'N/A'}
            </td>
            <td style="padding: 8px; border: 1px solid #aaa; font-size: 11px;">
              ${c.CaseStatus || 'N/A'}<br/>
              <span style="font-size: 10px; color: #555;">${c.Undersection || ''}</span>
            </td>
            <td style="padding: 8px; border: 1px solid #aaa; width: 220px; height: 50px; background-color: #fafafa;">
              <!-- Blank column for hand-written notes -->
            </td>
          </tr>
        `;
      });
    } else {
      rowsHtml = `
        <tr>
          <td colspan="6" style="padding: 20px; text-align: center; color: #666; font-style: italic;">
            No cases listed for today.
          </td>
        </tr>
      `;
    }

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <style>
            @page {
              size: landscape;
              margin: 10mm;
            }
            body {
              font-family: Arial, sans-serif;
              color: #222;
              line-height: 1.4;
              padding: 10px;
            }
            .header {
              text-align: center;
              border-bottom: 2px double #333;
              padding-bottom: 8px;
              margin-bottom: 15px;
            }
            .header h1 {
              margin: 0;
              font-size: 22px;
              text-transform: uppercase;
            }
            .header h2 {
              margin: 5px 0 0 0;
              font-size: 15px;
              color: #444;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 10px;
            }
            th {
              background-color: #eaeaea;
              color: #111;
              font-size: 12px;
              text-align: left;
              padding: 8px;
              font-weight: bold;
              border: 1px solid #aaa;
              text-transform: uppercase;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Daily Cause List</h1>
            <h2>Date: ${titleDate} &bull; Prepared for Junior Advocates</h2>
          </div>
          <table>
            <thead>
              <tr>
                <th style="width: 5%; text-align: center;">S.No</th>
                <th style="width: 25%;">Case Details</th>
                <th style="width: 20%;">Court & Judge</th>
                <th style="width: 10%; text-align: center;">Prev. Date</th>
                <th style="width: 15%;">Status / Sec</th>
                <th style="width: 25%;">Courtroom Notes</th>
              </tr>
            </thead>
            <tbody>
              ${rowsHtml}
            </tbody>
          </table>
        </body>
      </html>
    `;

    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: `Daily_Cause_List_${titleDate.replace(/[^a-zA-Z0-9]/g, '_')}`,
        UTI: 'com.adobe.pdf',
      });
    } else {
      console.warn("PDF sharing is not available on this platform.");
    }
  } catch (error) {
    console.error("Failed to export cause list to PDF:", error);
    throw error;
  }
};

/**
 * Generates a clean Case History PDF containing only all the previous dates, hearing logs, and records.
 */
export const exportCaseHistoryToPdf = async (caseDetails: CaseWithDetails): Promise<void> => {
  try {
    const timelineEvents = await getCaseTimelineEventsByCaseId(caseDetails.id);
    
    let timelineHtml = '';
    if (timelineEvents.length > 0) {
      timelineEvents.forEach((event, index) => {
        timelineHtml += `
          <tr>
            <td style="padding: 10px; border: 1px solid #ccc; text-align: center; font-weight: bold; width: 60px;">
              ${index + 1}
            </td>
            <td style="padding: 10px; border: 1px solid #ccc; font-weight: bold; width: 120px; color: #1E3A8A;">
              ${formatDate(event.hearing_date)}
            </td>
            <td style="padding: 10px; border: 1px solid #ccc; font-size: 14px;">
              ${event.notes || 'No notes/records logged for this date.'}
            </td>
          </tr>
        `;
      });
    } else {
      timelineHtml = `
        <tr>
          <td colspan="3" style="padding: 30px; text-align: center; color: #666; font-style: italic; border: 1px solid #ccc;">
            No hearing history dates or records logged yet.
          </td>
        </tr>
      `;
    }

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <style>
            body {
              font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
              color: #333;
              line-height: 1.5;
              padding: 20px;
            }
            .header {
              text-align: center;
              border-bottom: 2px solid #1E3A8A;
              padding-bottom: 12px;
              margin-bottom: 20px;
            }
            .header h1 {
              margin: 0;
              color: #1E3A8A;
              font-size: 24px;
              text-transform: uppercase;
              letter-spacing: 0.5px;
            }
            .header p {
              margin: 5px 0 0 0;
              color: #666;
              font-size: 14px;
            }
            .meta-section {
              background-color: #F3F4F6;
              border: 1px solid #E5E7EB;
              border-radius: 6px;
              padding: 15px;
              margin-bottom: 25px;
            }
            .meta-title {
              font-weight: bold;
              font-size: 16px;
              color: #1E3A8A;
              margin-bottom: 10px;
              text-transform: uppercase;
            }
            .meta-grid {
              display: grid;
              grid-template-columns: 1fr 1fr;
              gap: 10px;
              font-size: 14px;
            }
            .meta-item span {
              font-weight: bold;
              color: #555;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 15px;
            }
            th {
              background-color: #1E3A8A;
              color: #ffffff;
              text-align: left;
              padding: 10px;
              font-weight: bold;
              border: 1px solid #1E3A8A;
              font-size: 12px;
              text-transform: uppercase;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>CASE HEARING HISTORY & RECORDS</h1>
            <p>Generated by CaseDiary Application</p>
          </div>
          
          <div class="meta-section">
            <div class="meta-title">Case details</div>
            <div class="meta-grid">
              <div class="meta-item"><span>Case Title:</span> ${caseDetails.CaseTitle || 'N/A'}</div>
              <div class="meta-item"><span>Client Name:</span> ${caseDetails.ClientName || 'N/A'}</div>
              <div class="meta-item"><span>Case Number:</span> ${caseDetails.case_number || 'N/A'}</div>
              <div class="meta-item"><span>CNR Number:</span> ${caseDetails.CNRNumber || 'N/A'}</div>
              <div class="meta-item"><span>Court Name:</span> ${caseDetails.court_name || 'N/A'}</div>
              <div class="meta-item"><span>Case Type:</span> ${caseDetails.case_type_name || 'N/A'}</div>
            </div>
          </div>

          <div style="font-size: 16px; font-weight: bold; color: #1E3A8A; margin-bottom: 8px;">Previous Dates & Records Timeline</div>
          <table>
            <thead>
              <tr>
                <th style="text-align: center; width: 60px;">S.No</th>
                <th style="width: 120px;">Hearing Date</th>
                <th>Case Record / Court Proceedings Notes</th>
              </tr>
            </thead>
            <tbody>
              ${timelineHtml}
            </tbody>
          </table>
        </body>
      </html>
    `;

    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: `History_${caseDetails.CaseTitle || 'Case'}`,
        UTI: 'com.adobe.pdf',
      });
    } else {
      console.warn("PDF sharing is not available on this platform.");
    }
  } catch (error) {
    console.error("Failed to export case history to PDF:", error);
    throw error;
  }
};
