import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Alert } from "react-native";

import {
  AVAILABLE_CAUSE_LIST_FIELDS,
  getCauseListSelectedFields,
  getCauseListSortConfig,
  sortCasesForCauseList,
} from "./causeListConfig";
import { formatDate } from "./commonFunctions";
import { createNamedPdfFile, shareNamedPdf } from "./fileShareHelper";
import { CaseWithDetails, getCaseTimelineEventsByCaseId } from "../DataBase";

const appPromoFooterHtml = `
  <div style="margin-top: 30px; padding-top: 12px; border-top: 1px solid #E5E7EB; text-align: center; font-family: Arial, sans-serif;">
    <div style="display: inline-block; vertical-align: middle;">
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#1E3A8A" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" style="vertical-align: middle; margin-right: 6px;">
        <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path>
        <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path>
      </svg>
      <span style="font-weight: bold; color: #1E3A8A; font-size: 12px; vertical-align: middle; letter-spacing: 0.5px;">Advocase</span>
    </div>
    <div style="margin-top: 4px; font-size: 10px; color: #555;">
      Generated using <strong>Advocase</strong>. Get your digital case diary now at 
      <a href="https://play.google.com/store/apps/details?id=com.iamshiv.CaseDiary" style="color: #1E3A8A; text-decoration: underline; font-weight: bold;">Google Play Store</a>.
    </div>
  </div>
`;

/**
 * Generates a beautiful case summary and timeline PDF and opens the sharing dialog.
 *
 * @param caseDetails The case details object
 */
export const exportCaseToPdf = async (
  caseDetails: CaseWithDetails,
  navigation?: any
): Promise<void> => {
  try {
    const timelineEvents = await getCaseTimelineEventsByCaseId(caseDetails.id);

    let timelineHtml = "";
    if (timelineEvents.length > 0) {
      timelineEvents.forEach((event) => {
        timelineHtml += `
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #ddd; font-weight: bold; width: 120px;">
              ${formatDate(event.hearing_date)}
            </td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">
              ${event.notes || "No notes added"}
            </td>
          </tr>
        `;
      });
    } else {
      timelineHtml = `
        <tr>
          <td colspan="2" style="padding: 20px; text-align: center; color: #666; font-style: italic;">
            No hearings logged in history.
          </td>
        </tr>
      `;
    }

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <style>
            body {
              font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
              color: #333;
              line-height: 1.5;
              padding: 20px;
            }
            .header {
              text-align: center;
              border-bottom: 2px solid #3B82F6;
              padding-bottom: 15px;
              margin-bottom: 25px;
            }
            .header h1 {
              margin: 0;
              color: #1E3A8A;
              font-size: 26px;
            }
            .header p {
              margin: 5px 0 0 0;
              color: #666;
              font-size: 14px;
            }
            .section {
              margin-bottom: 25px;
            }
            .section-title {
              font-size: 18px;
              color: #1E3A8A;
              border-bottom: 1px solid #3B82F6;
              padding-bottom: 5px;
              margin-bottom: 12px;
              text-transform: uppercase;
              letter-spacing: 0.5px;
            }
            .info-grid {
              display: grid;
              grid-template-columns: 1fr 1fr;
              gap: 15px;
            }
            .info-item {
              margin-bottom: 10px;
            }
            .info-label {
              font-weight: bold;
              color: #555;
              font-size: 12px;
              text-transform: uppercase;
            }
            .info-value {
              font-size: 15px;
              color: #111;
              margin-top: 2px;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 10px;
            }
            th {
              background-color: #F3F4F6;
              color: #1E3A8A;
              text-align: left;
              padding: 10px;
              font-weight: bold;
              border-bottom: 2px solid #ddd;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>CASE SUMMARY SHEET</h1>
            <p>Generated by CaseDiary Application</p>
          </div>
          
          <div class="section">
            <div class="section-title">Case Metadata</div>
            <div class="info-grid">
              <div class="info-item">
                <div class="info-label">Case Title</div>
                <div class="info-value" style="font-weight: bold; font-size: 17px;">${caseDetails.CaseTitle || "N/A"}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Client Name</div>
                <div class="info-value">${caseDetails.ClientName || "N/A"}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Case Number / Year</div>
                <div class="info-value">${caseDetails.case_number || "N/A"} / ${caseDetails.case_year || "N/A"}</div>
              </div>
              <div class="info-item">
                <div class="info-label">CNR Number</div>
                <div class="info-value">${caseDetails.CNRNumber || "N/A"}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Court Name</div>
                <div class="info-value">${caseDetails.court_name || "N/A"}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Case Type</div>
                <div class="info-value">${caseDetails.case_type_name || "N/A"}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Next Hearing Date</div>
                <div class="info-value" style="color: #EF4444; font-weight: bold;">${formatDate(caseDetails.NextDate)}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Status</div>
                <div class="info-value">${caseDetails.CaseStatus || "N/A"}</div>
              </div>
            </div>
          </div>

          <div class="section">
            <div class="section-title">Timeline & Hearing History</div>
            <table>
              <thead>
                <tr>
                  <th>Hearing Date</th>
                  <th>Notes / Updates</th>
                </tr>
              </thead>
              <tbody>
                ${timelineHtml}
              </tbody>
            </table>
          </div>
          ${appPromoFooterHtml}
        </body>
      </html>
    `;

    // 1. Render HTML template to PDF file (Legal size by default)
    const { uri } = await Print.printToFileAsync({
      html: htmlContent,
      width: 612,
      height: 1008,
    });

    const docFileName = `Case_Summary_${caseDetails.CaseTitle || "Case"}${caseDetails.case_number ? `_${caseDetails.case_number}` : ""}`;
    const namedUri = await createNamedPdfFile(uri, docFileName);
    const docTitle = caseDetails.CaseTitle || "Case Summary";

    // 2. Open sharing/viewing options
    if (navigation) {
      Alert.alert(
        docTitle,
        "Choose an action for this PDF:",
        [
          {
            text: "Open in App",
            onPress: () => {
              navigation.navigate("PdfViewer", {
                pdfUri: namedUri,
                title: docTitle,
              });
            },
          },
          {
            text: "Share PDF",
            onPress: async () => {
              await shareNamedPdf(namedUri, docFileName, docTitle);
            },
          },
          {
            text: "Cancel",
            style: "cancel",
          },
        ]
      );
    } else {
      await shareNamedPdf(namedUri, docFileName, docTitle);
    }
  } catch (error) {
    console.error("Failed to export case to PDF:", error);
    throw error;
  }
};

/**
 * Helper to build a high-density, single-line-per-case cause list HTML table.
 */
const generateCauseListHtml = async (
  cases: any[],
  title: string,
  subtitle: string,
  selectedFieldIds?: string[],
  sortField?: string,
  sortDirection?: "asc" | "desc"
): Promise<string> => {
  const activeFieldIds =
    selectedFieldIds && selectedFieldIds.length > 0
      ? selectedFieldIds
      : await getCauseListSelectedFields();

  let activeSortField = sortField;
  let activeSortDirection = sortDirection || "asc";

  if (!activeSortField) {
    const savedSort = await getCauseListSortConfig();
    activeSortField = savedSort.field;
    activeSortDirection = savedSort.direction;
  }

  const sortedCases = sortCasesForCauseList(
    cases,
    activeSortField,
    activeSortDirection
  );

  const selectedFields = AVAILABLE_CAUSE_LIST_FIELDS.filter((f) =>
    activeFieldIds.includes(f.id)
  );

  // Width distribution:
  // S.No: 4% (Mandatory)
  // Blank Notes: 16% (Mandatory)
  // Selected columns share remaining 80% proportionally
  const S_NO_WIDTH = 4;
  const BLANK_NOTES_WIDTH = 16;
  const REMAINING_WIDTH = 100 - S_NO_WIDTH - BLANK_NOTES_WIDTH;

  const totalBaseWeight =
    selectedFields.reduce((sum, f) => sum + f.baseWidthPercent, 0) || 1;
  const columnsWithWidth = selectedFields.map((f) => ({
    ...f,
    widthPercent: (f.baseWidthPercent / totalBaseWeight) * REMAINING_WIDTH,
  }));

  // Build <thead>
  let theadHtml = `
    <tr>
      <th style="width: ${S_NO_WIDTH}%; text-align: center;">S.No</th>
  `;
  columnsWithWidth.forEach((col) => {
    theadHtml += `<th style="width: ${col.widthPercent.toFixed(1)}%; text-align: left;">${col.label}</th>`;
  });
  theadHtml += `
      <th style="width: ${BLANK_NOTES_WIDTH}%; text-align: left;">Note / Next Date</th>
    </tr>
  `;

  // Build <tbody>
  let tbodyHtml = "";
  const totalCols = 2 + columnsWithWidth.length;

  if (sortedCases.length > 0) {
    sortedCases.forEach((c, index) => {
      tbodyHtml += `<tr>`;
      // 1. S.No (Mandatory, 1 to N after sorting)
      tbodyHtml += `<td style="text-align: center; font-weight: bold;">${index + 1}</td>`;

      // 2. Selected dynamic columns (strictly single-line)
      columnsWithWidth.forEach((col) => {
        const rawVal = col.getValue(c);
        const escapedVal = String(rawVal)
          .replace(/&/g, "&amp;")
          .replace(/</g, "&lt;")
          .replace(/>/g, "&gt;");
        tbodyHtml += `<td title="${escapedVal}">${escapedVal}</td>`;
      });

      // 3. Last Blank Column for Handwriting (Mandatory)
      tbodyHtml += `<td class="blank-column"></td>`;
      tbodyHtml += `</tr>`;
    });
  } else {
    tbodyHtml = `
      <tr>
        <td colspan="${totalCols}" style="padding: 16px; text-align: center; color: #666; font-style: italic;">
          No cases found to display.
        </td>
      </tr>
    `;
  }

  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <style>
          @page {
            size: landscape;
            margin: 6mm 8mm;
          }
          * {
            box-sizing: border-box;
          }
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
            color: #1E293B;
            margin: 0;
            padding: 4px;
            font-size: 9px;
            background-color: #FFFFFF;
          }
          .header {
            text-align: center;
            border-bottom: 1.5px solid #0F172A;
            padding-bottom: 4px;
            margin-bottom: 8px;
          }
          .header h1 {
            margin: 0;
            font-size: 16px;
            font-weight: 800;
            color: #0F172A;
            text-transform: uppercase;
            letter-spacing: 0.5px;
          }
          .header h2 {
            margin: 2px 0 0 0;
            font-size: 11px;
            font-weight: 500;
            color: #475569;
          }
          table {
            width: 100%;
            table-layout: fixed;
            border-collapse: collapse;
            border: 1px solid #64748B;
          }
          th {
            background-color: #E2E8F0;
            color: #0F172A;
            font-size: 9px;
            font-weight: 700;
            padding: 3px 4px;
            border: 1px solid #94A3B8;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            text-transform: uppercase;
            height: 20px;
          }
          td {
            padding: 2px 4px;
            font-size: 8.5px;
            line-height: 1.15;
            height: 19px;
            max-height: 19px;
            border: 1px solid #CBD5E1;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            vertical-align: middle;
            color: #0F172A;
          }
          tr:nth-child(even) td {
            background-color: #F8FAFC;
          }
          td.blank-column {
            background-color: #FFFFFF;
          }
          @media print {
            body { -webkit-print-color-adjust: exact; }
            tr { page-break-inside: avoid; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${title}</h1>
          <h2>${subtitle}</h2>
        </div>
        <table>
          <thead>
            ${theadHtml}
          </thead>
          <tbody>
            ${tbodyHtml}
          </tbody>
        </table>
        ${appPromoFooterHtml}
      </body>
    </html>
  `;
};

/**
 * Exports today's cause list of cases to a structured PDF for junior advocates.
 * Includes a blank 'Notes' column on the right for manual handwriting.
 */
export const exportDailyCauseListToPdf = async (
  cases: any[],
  titleDate: string,
  navigation?: any,
  selectedFieldIds?: string[],
  sortField?: string,
  sortDirection?: "asc" | "desc"
): Promise<void> => {
  try {
    const htmlContent = await generateCauseListHtml(
      cases,
      "Daily Cause List",
      `Date: ${titleDate} • Prepared for Junior Advocates`,
      selectedFieldIds,
      sortField,
      sortDirection
    );

    const { uri } = await Print.printToFileAsync({
      html: htmlContent,
      width: 842,
      height: 595,
    });

    const docFileName = `Daily_Cause_List_${titleDate}`;
    const namedUri = await createNamedPdfFile(uri, docFileName);
    const docTitle = `Daily Cause List - ${titleDate}`;

    if (navigation) {
      setTimeout(() => {
        Alert.alert(
          docTitle,
          "Choose an action for this PDF:",
          [
            {
              text: "Open in App",
              onPress: () => {
                navigation.navigate("PdfViewer", {
                  pdfUri: namedUri,
                  title: docTitle,
                });
              },
            },
            {
              text: "Share PDF",
              onPress: async () => {
                await shareNamedPdf(namedUri, docFileName, docTitle);
              },
            },
            {
              text: "Cancel",
              style: "cancel",
            },
          ]
        );
      }, 350);
    } else {
      await shareNamedPdf(namedUri, docFileName, docTitle);
    }
  } catch (error) {
    console.error("Failed to export cause list to PDF:", error);
    throw error;
  }
};

/**
 * Generates a clean Case History PDF containing only all the previous dates, hearing logs, and records.
 */
export const exportCaseHistoryToPdf = async (
  caseDetails: CaseWithDetails,
  navigation?: any
): Promise<void> => {
  try {
    const timelineEvents = await getCaseTimelineEventsByCaseId(caseDetails.id);

    let timelineHtml = "";
    if (timelineEvents.length > 0) {
      timelineEvents.forEach((event, index) => {
        timelineHtml += `
          <tr>
            <td style="padding: 10px; border: 1px solid #ccc; text-align: center; font-weight: bold; width: 60px;">
              ${index + 1}
            </td>
            <td style="padding: 10px; border: 1px solid #ccc; font-weight: bold; width: 120px; color: #1E3A8A;">
              ${formatDate(event.hearing_date)}
            </td>
            <td style="padding: 10px; border: 1px solid #ccc; font-size: 14px;">
              ${event.notes || "No notes/records logged for this date."}
            </td>
          </tr>
        `;
      });
    } else {
      timelineHtml = `
        <tr>
          <td colspan="3" style="padding: 30px; text-align: center; color: #666; font-style: italic; border: 1px solid #ccc;">
            No hearing history dates or records logged yet.
          </td>
        </tr>
      `;
    }

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <style>
            body {
              font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
              color: #333;
              line-height: 1.5;
              padding: 20px;
            }
            .header {
              text-align: center;
              border-bottom: 2px solid #1E3A8A;
              padding-bottom: 12px;
              margin-bottom: 20px;
            }
            .header h1 {
              margin: 0;
              color: #1E3A8A;
              font-size: 24px;
              text-transform: uppercase;
              letter-spacing: 0.5px;
            }
            .header p {
              margin: 5px 0 0 0;
              color: #666;
              font-size: 14px;
            }
            .meta-section {
              background-color: #F3F4F6;
              border: 1px solid #E5E7EB;
              border-radius: 6px;
              padding: 15px;
              margin-bottom: 25px;
            }
            .meta-title {
              font-weight: bold;
              font-size: 16px;
              color: #1E3A8A;
              margin-bottom: 10px;
              text-transform: uppercase;
            }
            .meta-grid {
              display: grid;
              grid-template-columns: 1fr 1fr;
              gap: 10px;
              font-size: 13px;
            }
            .meta-item span {
              font-weight: bold;
              color: #1E3A8A;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 15px;
            }
            th {
              background-color: #1E3A8A;
              color: #ffffff;
              text-align: left;
              padding: 10px;
              font-weight: bold;
              border: 1px solid #1E3A8A;
              font-size: 12px;
              text-transform: uppercase;
            }
            @page {
              size: landscape;
              margin: 10mm;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>CASE HEARING HISTORY & RECORDS</h1>
            <p>Generated by CaseDiary Application</p>
          </div>
          
          <div class="meta-section">
            <div class="meta-title">Case details</div>
            <div class="meta-grid">
              <div class="meta-item"><span>Case Title:</span> ${caseDetails.CaseTitle || "N/A"}</div>
              <div class="meta-item"><span>Client Name:</span> ${caseDetails.ClientName || "N/A"}</div>
              <div class="meta-item"><span>Case Number:</span> ${caseDetails.case_number || "N/A"}</div>
              <div class="meta-item"><span>CNR Number:</span> ${caseDetails.CNRNumber || "N/A"}</div>
              <div class="meta-item"><span>Court Name:</span> ${caseDetails.court_name || "N/A"}</div>
              <div class="meta-item"><span>Case Type:</span> ${caseDetails.case_type_name || "N/A"}</div>
            </div>
          </div>

          <div style="font-size: 16px; font-weight: bold; color: #1E3A8A; margin-bottom: 8px;">Previous Dates & Records Timeline</div>
          <table>
            <thead>
              <tr>
                <th style="text-align: center; width: 60px;">S.No</th>
                <th style="width: 120px;">Hearing Date</th>
                <th>Case Record / Court Proceedings Notes</th>
              </tr>
            </thead>
            <tbody>
              ${timelineHtml}
            </tbody>
          </table>
          ${appPromoFooterHtml}
        </body>
      </html>
    `;

    const { uri } = await Print.printToFileAsync({
      html: htmlContent,
      width: 842,
      height: 595,
    });

    const docFileName = `Hearing_History_${caseDetails.CaseTitle || "Case"}${caseDetails.case_number ? `_${caseDetails.case_number}` : ""}`;
    const namedUri = await createNamedPdfFile(uri, docFileName);
    const docTitle = `History - ${caseDetails.CaseTitle || "Case"}`;

    if (navigation) {
      setTimeout(() => {
        Alert.alert(
          docTitle,
          "Choose an action for this PDF:",
          [
            {
              text: "Open in App",
              onPress: () => {
                navigation.navigate("PdfViewer", {
                  pdfUri: namedUri,
                  title: docTitle,
                });
              },
            },
            {
              text: "Share PDF",
              onPress: async () => {
                await shareNamedPdf(namedUri, docFileName, docTitle);
              },
            },
            {
              text: "Cancel",
              style: "cancel",
            },
          ]
        );
      }, 350);
    } else {
      await shareNamedPdf(namedUri, docFileName, docTitle);
    }
  } catch (error) {
    console.error("Failed to export case history to PDF:", error);
    throw error;
  }
};

/**
 * Exports undated cases list to a structured Landscape PDF for junior advocates.
 * Includes a blank 'Note / Next Date' column on the right for manual handwriting.
 */
export const exportUndatedCasesToPdf = async (
  cases: any[],
  navigation?: any,
  selectedFieldIds?: string[],
  sortField?: string,
  sortDirection?: "asc" | "desc"
): Promise<void> => {
  try {
    const htmlContent = await generateCauseListHtml(
      cases,
      "Undated Cases List",
      "Prepared for Junior Advocates",
      selectedFieldIds,
      sortField,
      sortDirection
    );

    const { uri } = await Print.printToFileAsync({
      html: htmlContent,
      width: 842,
      height: 595,
    });

    const dateStr = formatDate(new Date());
    const docFileName = `Undated_Cases_List_${dateStr}`;
    const namedUri = await createNamedPdfFile(uri, docFileName);
    const docTitle = "Undated Cases List";

    if (navigation) {
      setTimeout(() => {
        Alert.alert(docTitle, "Choose an action for this PDF:", [
          {
            text: "Open in App",
            onPress: () => {
              navigation.navigate("PdfViewer", {
                pdfUri: namedUri,
                title: docTitle,
              });
            },
          },
          {
            text: "Share PDF",
            onPress: async () => {
              await shareNamedPdf(namedUri, docFileName, docTitle);
            },
          },
          {
            text: "Cancel",
            style: "cancel",
          },
        ]);
      }, 350);
    } else {
      await shareNamedPdf(namedUri, docFileName, docTitle);
    }
  } catch (error) {
    console.error("Failed to export undated cases list to PDF:", error);
    throw error;
  }
};
