// utils/transliterationService.ts

// Extensive local dictionary of Indian legal and litigation terms in Hindi for offline instant conversion
const LOCAL_LEGAL_DICTIONARY: { [key: string]: string[] } = {
  // Common Legal Terms
  tarikh: ["तारीख", "तारिख"],
  taarikh: ["तारीख"],
  tariq: ["तारीख"],
  peshi: ["पेशी"],
  vakalatnama: ["वकालतनामा"],
  vakaalat: ["वकालत"],
  vakeelpatra: ["वकील पत्र"],
  faisla: ["फैसला"],
  zamanat: ["जमानत"],
  zamalat: ["जमानत"],
  vail: ["बेल", "जमानत"],
  bail: ["बेल", "जमानत"],
  kanoon: ["कानून"],
  kanun: ["कानून"],
  kanooni: ["कानूनी"],
  kanoonan: ["कानूनन"],
  gairkanooni: ["गैरकानूनी"],
  adalat: ["अदालत"],
  court: ["कोर्ट"],
  kort: ["कोर्ट"],
  judge: ["जज"],
  jaj: ["जज"],
  magistrate: ["मजिस्ट्रेट"],
  nyayik: ["न्यायिक"],
  muqadma: ["मुकदमा"],
  mukadma: ["मुकदमा"],
  vakeel: ["वकील"],
  vakil: ["वकील"],
  arzi: ["अर्जी"],
  dastavez: ["दस्तावेज"],
  dastavej: ["दस्तावेज"],
  saboot: ["सबूत"],
  sabut: ["सबूत"],
  sabooto: ["सबूतों"],
  gawah: ["गवाह"],
  gawahi: ["गवाही"],
  gavaho: ["गवाहों"],
  gavahi: ["गवाही"],
  bayan: ["बयान"],
  shapath: ["शपश"],
  shapathpatra: ["शपथ पत्र"],
  halafnama: ["हलफनामा"],
  saza: ["सजा"],
  sazaye: ["सजाएं"],
  jurmana: ["जुर्माना"],
  police: ["पुलिस"],
  pulice: ["पुलिस"],
  thana: ["थाना"],
  daroga: ["दरोगा"],
  notice: ["नोटिस"],
  client: ["क्लाइंट", "मुवक्किल"],
  case: ["केस", "मुकदमा"],
  kes: ["केस"],
  order: ["ऑर्डर", "आदेश"],
  appeal: ["अपील"],
  petition: ["पिटीशन", "याचिका"],
  plaint: ["वाद पत्र", "प्लेन्ट"],
  written: ["लिखित"],
  statement: ["कथन", "स्टेटमेंट"],
  application: ["एप्लीकेशन", "प्रार्थना पत्र"],
  summons: ["समन"],
  saman: ["समन"],
  warrant: ["वारंट"],
  fir: ["एफआईआर"],
  dhara: ["धारा"],
  dharaaye: ["धाराएं"],
  section: ["सेक्शन", "धारा"],
  act: ["एक्ट", "कानून"],
  ipc: ["आईपीसी"],
  crpc: ["सीआरपीसी"],
  cpc: ["सीपीसी"],
  nyay: ["न्याय"],
  nyayalaya: ["न्यायालय"],
  nyayadhish: ["न्यायाधीश"],
  vivad: ["विवाद"],
  vivadit: ["विवादित"],
  samjhauta: ["समझौता"],
  apradh: ["अपराध"],
  apradhi: ["अपराधी"],
  shikayat: ["शिकायत"],
  shikayatkarta: ["शिकायतकर्ता"],
  aarop: ["आरोप"],
  aaropi: ["आरोपी"],
  dosh: ["दोष"],
  doshi: ["दोषी"],
  riha: ["रिहा"],
  rihai: ["रिहाई"],
  hirasat: ["हिरासत"],
  hiraasat: ["हिरासत"],
  remand: ["रिमांड"],
  dalil: ["दलील"],
  daleel: ["दलील"],
  dalile: ["दलीलें"],
  daleele: ["दलीलें"],
  sunwai: ["सुनवाई"],
  sunvai: ["सुनवाई"],
  karyawahi: ["कार्यवाही"],
  karyavahi: ["कार्यवाही"],
  aadesh: ["आदेश"],
  nirdesh: ["निर्देश"],
  nirnay: ["निर्णय"],
  antim: ["अंतिम"],
  antarim: ["अंतरिम"],
  stay: ["स्टे", "रोक"],
  rok: ["रोक"],
  kharij: ["खारिज"],
  manzoor: ["मंजूर"],
  manjur: ["मंजूर"],
  aswikar: ["अस्वीकार"],
  dakhil: ["दाखिल"],
  prastut: ["प्रस्तत"],
  prarthna: ["प्रार्थना"],
  yachika: ["याचिका"],
  yachikakarta: ["याचिकाकर्ता"],
  prativadi: ["प्रतिवादी"],
  vadi: ["वादी"],
  aaroppatra: ["आरोप पत्र"],
  chargesheet: ["चार्जशीट"],
  jurm: ["जुर्म"],
  gunehgar: ["गुनहगार"],
  gunahgar: ["गुनहगार"],
  chori: ["चोरी"],
  dhokhadhadi: ["धोखाधड़ी"],
  gaddari: ["गद्दारी"],
  hatya: ["हत्या"],
  khoon: ["खून"],
  hamla: ["हमला"],
  dhamki: ["धमकी"],
  shanti: ["शांति"],
  suraksha: ["सुरक्षा"],
  mudda: ["मुद्दा"],
  tathya: ["तथ्य"],
  jirah: ["जिरह"],
  bahas: ["बहस"],
  davedar: ["दावेदार"],
  dava: ["दावा"],
  malik: ["मालिक"],
  kirayedar: ["किरायेदार"],
  kabza: ["कब्जा"],
  sampatti: ["संपत्ति"],
  bhoomi: ["भूमि"],
  bhumi: ["भूमि"],
  jamin: ["जमीन"],
  jameen: ["जमीन"],
  registry: ["रजिस्ट्री"],
  pattadar: ["पट्टादार"],
  pattadarnama: ["पट्टानामा"],
  bayanama: ["बैनामा"],
  batwara: ["बंटवारा"],
  wasiyat: ["वसीयत"],
  vasiyat: ["वसीयत"],
  uttaradhikari: ["उत्तराधिकारी"],
  haq: ["हक"],
  hissa: ["हिस्सा"],
  nuksan: ["नुकसान"],
  nuxan: ["नुकसान"],
  nuksaan: ["नुकसान"],
  muavza: ["मुआवजा"],
  harjana: ["हर्जाना"],
  denadari: ["देनदारी"],
  karza: ["कर्ज"],
  karj: ["कर्ज"],
  bank: ["बैंक"],
  khata: ["खाता"],
  cheque: ["चेक"],
  chek: ["चेक"],
  bounce: ["बाउंस"],
  dhandhli: ["धांधली"],
  rishwat: ["रिश्वत"],
  bhrashtachar: ["भ्रष्टाचार"],
  adhiniyam: ["अधिनियम"],
  niyam: ["नियम"],
  sanshodhan: ["संशोधन"],
  samvidhan: ["संविधान"],
  maulik: ["मौलिक"],
  kartavya: ["कर्तव्य"],
  sansad: ["संसद"],
  vidhayika: ["विधायिका"],
  karyapalika: ["कार्यपालिका"],
  sarkar: ["सरकार"],
  shasan: ["शासन"],
  prashasan: ["प्रशासन"],
  nagarnigam: ["नगर निगम"],
  panchayat: ["पंचायत"],
  pradhan: ["प्रधान"],
  sarpanch: ["सरपंच"],
  patwari: ["पटवारी"],
  lekhpal: ["लेखपाल"],
  tehsildar: ["तहसीलदार"],
  collector: ["कलेक्टऱ"],
  daish: ["देश"],
  rajya: ["राज्य"],
  zila: ["जिला"],
  jila: ["जिला"],
  karyalaya: ["कार्यालय"],
  sewa: ["सेवा"],
  seva: ["सेवा"],
  niyukti: ["नियुक्ति"],
  pad: ["पद"],
  sthanantaran: ["स्थानांतरण"],
  sewanivrit: ["सेवानिवृत्त"],
  pension: ["पेंशन"],
  vibhag: ["विभाग"],
  mantralaya: ["मंत्रालय"],
  aayog: ["आयोग"],
  samiti: ["समिति"],
  sadasya: ["सदस्य"],
  sabhapati: ["सभापति"],
  baithak: ["बैठक"],
  chunav: ["चुनाव"],
  chunaav: ["चुनाव"],
  matdan: ["मतदान"],
  ummedwar: ["उम्मीदवार"],
  ummidwar: ["उम्मीदवार"],
  neta: ["नेता"],
  mantri: ["मंत्री"],
  mukhya: ["मुख्य"],
  rashtrapati: ["राष्ट्रपति"],
  rajyapal: ["राज्यपाल"],
  upbhokta: ["उपभोक्ता"],
  grahak: ["ग्राहक"],
  vyapari: ["व्यापारी"],
  sauda: ["सौदा"],
  shart: ["शर्त"],
  sart: ["शर्त"],
  sharte: ["शर्तें"],
  sarte: ["शर्तें"],
  ullanghan: ["उल्लंघन"],
  khatra: ["खतरा"],
  kshtipurti: ["क्षतिपूर्ति"],
  bhugtan: ["भुगतान"],
  baya: ["बयाना"],
  rakam: ["रकम"],
  paisa: ["पैसा"],
  paise: ["पैसे"],
  rupiya: ["रुपया"],
  rupaye: ["रुपये"],
  vyaj: ["ब्याज़"],
  byaj: ["ब्याज़"],
  dar: ["दर"],
  kisht: ["किश्त"],
  dene: ["देने"],
  lene: ["लेने"],
  kharid: ["खरीद"],
  khareed: ["खरीद"],
  bech: ["बेच"],
  bikri: ["बिक्री"],
  anubandh: ["अनुबंध"],
  krar: ["करार"],
  karar: ["करार"],
  sanyukt: ["संयुक्त"],
  sajhedar: ["साझेदार"],
  sajhedari: ["साझेदारी"],
  company: ["कंपनी"],
  partner: ["पार्टनर"],
  share: ["शेयर"],
  laabh: ["लाभ"],
  labh: ["लाभ"],
  hani: ["हानि"],
  ghata: ["घाटा"],
  kar: ["कर"],
  shulk: ["शुल्क"],
  rasid: ["रसीद"],
  raseed: ["रसीद"],
  panjiyan: ["पंजीकरण"],
  stamp: ["स्टांप"],
  paper: ["कागज", "पेपर"],
  nirikshan: ["निरीक्षण"],
  jaanch: ["जांच"],
  janch: ["जांच"],
  puchtach: ["पूछताछ"],
  sach: ["सच"],
  jhooth: ["झूठ"],
  jhut: ["झूठ"],
  fareb: ["फरेब"],
  sazish: ["साजिश"],
  shadyantra: ["षड्यंत्र"],
  maarpeet: ["मारपीट"],
  jhagda: ["झगड़ा"],
  danga: ["दंगा"],
  curfew: ["कर्फ्यू"],
  naka: ["नाका"],
  giraftari: ["गिरफ्तारी"],
  kaid: ["कैद"],
  jail: ["जेल"],
  bandi: ["बंदी"],
  manjoor: ["मंजूर"],
};

// Simple local cache to prevent redundant API queries for the same word
const transliterationCache: { [key: string]: string[] } = {};

/**
 * Queries Google's public Input Tools API or checks local dictionary to get Hindi phonetic candidates for a given English word.
 * 
 * @param word The word typed in English phonetics (e.g., "tarikh")
 * @returns A promise resolving to an array of Hindi candidates (e.g., ["तारीख", "तारिख"])
 */
export const getHindiCandidates = async (word: string): Promise<string[]> => {
  const trimmed = word.trim().toLowerCase();
  if (!trimmed) return [];

  // 1. Check offline litigation dictionary first
  if (LOCAL_LEGAL_DICTIONARY[trimmed]) {
    return LOCAL_LEGAL_DICTIONARY[trimmed];
  }

  // 2. Return cached result if available
  if (transliterationCache[trimmed]) {
    return transliterationCache[trimmed];
  }

  // Basic validation to avoid sending digits, punctuation, or special chars to the translation API
  if (/^[0-9\W_]+$/.test(trimmed)) {
    return [trimmed];
  }

  try {
    // Requesting num=8 for more candidates on typing
    const url = `https://inputtools.google.com/request?text=${encodeURIComponent(trimmed)}&itc=hi-t-i0-und&num=8`;
    const response = await fetch(url, {
      method: "GET",
      headers: {
        Accept: "application/json",
      },
    });

    if (!response.ok) {
      throw new Error(`Transliteration API failed with status ${response.status}`);
    }

    const data = await response.json();

    // Parse Google Input Tools response:
    // Format: ["SUCCESS", [ [ "original_word", [ "candidate1", "candidate2", ... ], [], {} ] ]]
    if (
      data &&
      data[0] === "SUCCESS" &&
      data[1] &&
      data[1][0] &&
      data[1][0][1]
    ) {
      const candidates = data[1][0][1] as string[];
      transliterationCache[trimmed] = candidates;
      return candidates;
    }
  } catch (error) {
    console.warn("Failed to fetch Hindi candidates from transliteration service:", error);
  }

  return [];
};

